version: '3'

services:
  # centos:
  #   container_name: centos
  #   build: ./docker/centos
  #   tty: true
  #   ports:
  #     - 80:80
  #   privileged: true
  #   volumes:
  #     - ./server:/usr/share/nginx/html
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  # rtmp:
  #   container_name: rtmp
  #   build: ./docker/rtmp
  #   tty: true
  #   ports:
  #     - 80:80
  #   privileged: true
  #   volumes:
  #     - ./server/rtmp_server:/usr/local/nginx/html
  #     - ./server/Streaming:/Streaming
  #     # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  nginx-streaming-rtmp:
    container_name: nginx-streaming-rtmp
    build: ./docker/streaming
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    volumes:
      - ./docker/certs:/opt/certs



  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #   - 80:80
  #   volumes:
  #   - ./server:/var/www
  #   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #   - centos

  # db:
  #   image: mysql:5.7
  #   container_name: db-host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: database
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #   - ./docker/db/data:/var/lib/mysql
  #   - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #   - ./docker/db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #   - 3306:3306